### ISSUE TITLE
Broken colors in some themes

### ISSUE THREAD

**Issue by duongdominhchau** [simov/markdown-viewer#146]
Hi, today I use this extension again after a long time and notice that the text color is broken for some themes, specifically they are:

- **GitHub**:
![image](https://user-images.githubusercontent.com/56427890/117127656-8ddaf900-adc6-11eb-8a97-214e5dfa633f.png)
- **Radar**:
![image](https://user-images.githubusercontent.com/56427890/117127765-ba8f1080-adc6-11eb-9067-b1cb4883fcfe.png)
- **Markdown7**:
![image](https://user-images.githubusercontent.com/56427890/117127901-e7432800-adc6-11eb-8996-6920dc7a53a7.png)
- **Markdown-Alt**:
![image](https://user-images.githubusercontent.com/56427890/117127934-f4601700-adc6-11eb-99a1-26341adb94af.png)

Other themes may not have the border, but they work fine, like **GitHub Dark**:
![image](https://user-images.githubusercontent.com/56427890/117128140-3b4e0c80-adc7-11eb-9e92-1a60b01f8a47.png)

### Environment
- OS: ArchLinux
- Firefox Developer Edition 89.0b8
- Extension version 4.0 last updated on March 23, 2021

**Comment by simov** [comment]
Interesting, are you using dark mode in FF or in your OS? I guess those css styles are picking this up somehow.

**Comment by duongdominhchau** [comment]
I set all of them to use dark theme. I inspected the source of that color and Firefox shows that it comes from `resource://content-accessible/plaintext.css`. This is the whole file:

```css
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

pre {
  white-space: pre-wrap;
  word-wrap: break-word;
  -moz-control-character-visibility: visible;
}

.nowrap pre {
  white-space: pre;
}

/* Make text go with the rules of dir=auto, but allow it to be overriden if 'Switch Text Direction' is triggered */
html:not([dir]) pre { /* Not a UA sheet, so doesn't use :-moz-has-dir-attr */
  unicode-bidi: plaintext;
}

@-moz-document unobservable-document() {
  @media (prefers-color-scheme: dark) {
    :root {
      /* in-content-page-{color, background} for dark theme. */
      background: rgb(28,27,34);
      color: rgb(251,251,254);
    }

    @media not (-moz-proton) {
      :root {
        background: #2a2a2e;
        color: rgb(249, 249, 250);
      }
    } /** END !proton **/
  }
}

/* NOTE(emilio): For some reason some pages, mainly bing.com, load a bunch of
 * scripts in zero-size <object> elements, see bug 1548449.
 *
 * Line-breaking such documents is useless and pretty expensive, so only render
 * them if there's a viewport. Sigh.
 */
@media (width: 0) or (height: 0) {
  :root {
    display: none;
  }
}
```

I tried disabling this extension and refresh, the link to that file is still there. I tried switching to other Firefox themes like the Default and the Light theme, all of them have this problem, so this CSS is not injected by the Firefox theme. I suspect my other extensions so I also disable them all, but the CSS is still injected. I'm out of clue for now.

By the way, should I report things like this? I notice that sometimes Firefox Developer Edition has breaking change in one version and get reverted in the next version, then get re-added again in another next version.
