### ISSUE TITLE
Suggestion to wrap long lines in code block when printing

### ISSUE THREAD

**Issue by lpk-py** [simov/markdown-viewer#193]
I guess it can be done by adding 

```css
@media print {
    pre {
        white-space: pre-wrap;
    }
}
```

to the css files.
